# version: "3.8"

# services:
#   api:
#     build:
#       context: ./
#     ports:
#       - "7777:7777"
#     restart: always
#     container_name: api
#     depends_on:
#       - mongo
#     extra_hosts:
#       - "host.docker.internal:host-gateway"
#   # db:
#   #   build:
#   #     context: ./db
#   #   container_name: db
#   #   ports:
#   #     - "3306:3306"
#   #   command: --default-authentication-plugin=mysql_native_password
#   #   restart: always
#   #   extra_hosts:
#   #     - "host.docker.internal:host-gateway"
#   mongo:
#     build: ./db/mongo
#     container_name: mongo-db

#     # environment:
#     #   - MYSQL_ROOT_PASSWORD=test

version: "3.8"

networks:
  my_network:
    driver: bridge

services:
  api:
    build:
      context: ./
    ports:
      - "7777:7777"
    restart: always
    container_name: api
    depends_on:
      - mongo
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - my_network

  mongo:
    build: ./db/mongo
    container_name: mongo-db
    ports:
      - "27017:27017"
    networks:
      - my_network
