version: "3.8"

services:
  api:
    build:
      context: ./
    ports:
      - "7777:7777"
    restart: always
    container_name: api
    depends_on:
      - db
  db:
    build:
      context: ./db
    container_name: db
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    # environment:
    #   - MYSQL_ROOT_PASSWORD=test
